version: '3'

services:
  api:
    image: langgenius/dify-api:0.7.1
    restart: always

  worker:
    image: langgenius/dify-api:0.7.1
    restart: always

  web:
    image: langgenius/dify-web:0.7.1
    restart: always

  sandbox:
    image: langgenius/dify-sandbox:0.2.29
    restart: always

